export interface IEditInfo{
    nome?: string,
    cpf?: string,
    endereco?: string,
    telefone?: string,
    dataPagamento?: string,
    item: any,
    opened?: boolean,
    janeiro: boolean,
    fevereiro: boolean,
    marco: boolean,
    abril: boolean,
    maio: boolean,
    junho: boolean,
    julho: boolean,
    agosto: boolean,
    setembro: boolean,
    outubro: boolean,
    novembro: boolean,
    dezembro: boolean,
    subtitle: string,
    edited?: boolean
}